apiVersion: batch/v1
kind: Job
metadata:
  name: music-generation-job
  namespace: music-app
  labels:
    app: music-app
    component: generator
spec:
  template:
    metadata:
      labels:
        app: music-app
        component: generator
    spec:
      restartPolicy: OnFailure
      containers:
      - name: music-generator
        image: music-app:latest
        command: ["python", "gen.py"]
        env:
        - name: OUTPUT_PATH
          value: "/app/output"
        - name: GENERATION_MODE
          value: "batch"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: output-volume
          mountPath: /app/output
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: music-output-pvc
  backoffLimit: 3
  completions: 1
  parallelism: 1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-output-pvc
  namespace: music-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard